### ISSUE TITLE
Define specific toolchain to be used for CV32E20 simulation verification

### ISSUE THREAD

**Issue by DBees** [openhwgroup/cve2#195]
This task is complete when the development team agrees on the specific GCC or LLVM toolchain to be used for CV32E20 simulation verification.  It is expected to be one of the [CORE-V top-of-tree compilers](https://www.embecosm.com/resources/tool-chain-downloads/#corev) toolchains provided by [Embecosm](https://www.embecosm.com/).

**Comment by MikeOpenHWGroup** [comment]
My proposal:
- Always use the latest version of the [CORE-V top-of-tree compilers](https://www.embecosm.com/resources/tool-chain-downloads/#corev) published by Embecosm.
- Specify the specific toolchain used to close coverage in the v1.0.0 "RTL Freeze" checklist.

**Comment by MikeOpenHWGroup** [comment]
Discussed with the team.  We are aligned.  Marking task as "Complete".
