### ISSUE TITLE
Make Sleep Unit, remove output port core_busy_o and add core_sleep_o

### ISSUE THREAD

**Issue by davideschiavone** [openhwgroup/cve2#2]
cv32e40p has a sleep unit that includes the clock gating cell, cve2 should not rely on external clock gating cells but it should have its own and manage the clock internally.

Also, the core should report outside when it is sleeping.

**Comment by joecircello** [comment]
Lee Hoff and I discussed this issue on Dec 5, 2022 and agree with Davide's proposal. Proposed new output signal is core_sleep_o. This is documented in ../cve2/issues/6

**Comment by davideschiavone** [comment]
done here a439ef7ad9da23e861850d6737646b0c1f08732a and 9abe653e1b8e226aabb6dc7f03b0bb0821e45d12
